### PR TITLE
Map Template can read gmApiKey and mapboxAccessToken from AppConfig

### PR DESCRIPTION
**Pull request by ammapspeople**
For the Map Template readme, update prop descriptions for gmApiKey and mapboxAccessToken, amphasizing that it can also be read from the MapsIndoors AppConfig.

### CODE REVIEW

**Comment by andreeaceachir142** [comment]
@ammapspeople This page should probably be updated as well, under the query parameters https://docsbeta.mapsindoors.com/~/revisions/Y8XwM9VNVWXWWrdkbz1s/products/fast-track-maptemplate/configuration/query-parameters

**Comment by ammapspeople** [comment]
> @ammapspeople This page should probably be updated as well, under the query parameters https://docsbeta.mapsindoors.com/~/revisions/Y8XwM9VNVWXWWrdkbz1s/products/fast-track-maptemplate/configuration/query-parameters

@andreeaceachir142 Updated.

**Review by andreeaceachir142 — APPROVED** [review]
✅

**Comment by ammapspeople** [comment]
Do not merge until https://github.com/MapsPeople/web-ui/pull/282 is available in the Map Template stable tag.

**Pull request closed without merging**
